--- #YAML:1.0
name:                Test-MockTime-DateCalc
version:             1
abstract:            Fake date/time for Date::Calc functions.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Calc:                    4
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
recommends:
    Test::MockTime: 0.12
optional_features:
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Test::Pod: 1.00
no_index:
    directory:
        - devel
        - t
resources:
    homepage: http://www.geocities.com/user42_kevin/test-mocktime-datecalc/index.html
    license: http://www.gnu.org/licenses/#GPL
